weights_path: 'weights/best-scoring.pt'
classes: ['basketball', 'rim', 'made']
# input: 'videos/nba1.mp4'
# input: 'videos/amateur2.mp4'
input: 'videos/fail1.mp4'
save_video: False
output_path: 'output'
upload_path: 'uploads'
output_width: 1280
output_height: 720
