weights_path: "weights/20250115best.pt"
# weights_path: "weights/03102025_best.pt"
weights_path_shoot: "weights/03102025_best.pt"
classes: ["basketball", "person", "rim", "shoot"]
classes_shoot: ["ball", "person", "rim", "shoot"]
# input: "uploads/nba1.mp4"
# input: 'uploads/amateur2.mp4'
# input: "/home/fyp_gch6/jason/testing_video/jch_4.MP4"
# input: "/home/fyp_gch6/jason/testing_video/nba_3.mp4"
# input: "/home/fyp_gch6/jason/testing_video/amateur_line.mp4"
# input: "/home/fyp_gch6/jason/data_gen_vids/hl_prof_2_converted.mp4"
# input: "/home/fyp_gch6/jason/data_gen_vids/hl_ama_la_2.mp4"
input: "/home/fyp_gch6/jason/data_gen_vids/fg_ama_ha_1.mp4"

save_video: False
output_path: "output"
upload_path: "uploads"
data_path: "data"
report_path: "reports"
resource_path: "resources"
output_width: 1280
output_height: 720
iou_threshold: 0.4
screenshot_path: "screenshots"
screenshot: False
flask_port: 5554
